name: Download datos nomivac
 
on:
  workflow_dispatch:
  schedule:
    - cron:  '12,22,32,42,52 * * * *'
 
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Get data nomivac from portal
      run: |-
        local_last_mod=$(cat last_modified_nomivac.txt)
        local_last_mod_ctime=$(date --date="$local_last_mod" +%s)
        current_last_mod=$(curl --silent --head https://sisa.msal.gov.ar/datos/descargas/covid-19/files/datos_nomivac_covid19.zip | grep "Last-Modified:" | cut -d ' ' -f1 --complement)
        current_last_mod_ctime=$(date --date="$current_last_mod" +%s)
        if [[ $local_last_mod_ctime -lt $current_last_mod_ctime ]] ; then
          curl --retry 3 --retry-delay 10 'https://sisa.msal.gov.ar/datos/descargas/covid-19/files/datos_nomivac_covid19.zip' --output datos_nomivac_covid19.zip
          unzip datos_nomivac_covid19.zip
          rm datos_nomivac_covid19.zip
          echo $current_last_mod > last_modified_nomivac.txt
        fi
    - name: Agrupado 1
      if: hashFiles('datos_nomivac_covid19.csv') != ''
      run: |-
        head -1 datos_nomivac_covid19.csv | awk -F, '{print $7","$2","$1","$14",cantidad"}' > datos_nomivac_covid19_agrupados_edad_sexo_dosis.csv
        awk -F, '{if (NR!=1) a[$7","$2","$1","$14]++}END{for(i in a) { print i"," "\"" a[i] "\"" }}' datos_nomivac_covid19.csv | sort -k1 >> datos_nomivac_covid19_agrupados_edad_sexo_dosis.csv
        sed -i -r 's/,orden_dosis,cantidad/,"orden_dosis","cantidad"/; s/,([12]),/,"\1",/gm;t' datos_nomivac_covid19_agrupados_edad_sexo_dosis.csv
    - name: Agrupado 2
      if: hashFiles('datos_nomivac_covid19.csv') != ''
      run: |-
        echo -n '"count",' > datos_nomivac_covid19_sin_fecha_sin_lote.csv
        head -1 datos_nomivac_covid19.csv | cut -d, -f11,15 --complement >> datos_nomivac_covid19_sin_fecha_sin_lote.csv
        tail -n +2 datos_nomivac_covid19.csv | cut -d, -f11,15 --complement | sort | uniq -c | sed 's/^ *//g; s/ /,/' >> datos_nomivac_covid19_sin_fecha_sin_lote.csv
    - name: Agrupado 3
      if: hashFiles('datos_nomivac_covid19.csv') != ''
      run: |-
        echo -n '"count",' > datos_nomivac_covid19_por_fecha_y_dosis.csv
        head -1 datos_nomivac_covid19.csv | cut -d, -f7,11,14 >> datos_nomivac_covid19_por_fecha_y_dosis.csv
        tail -n +2 datos_nomivac_covid19.csv | cut -d, -f7,11,14 | sort | uniq -c | sed 's/^ *//g; s/ /,/' >> datos_nomivac_covid19_por_fecha_y_dosis.csv
        sed -i -r 's/,orden_dosis/,"orden_dosis"/' datos_nomivac_covid19_por_fecha_y_dosis.csv
    - name: Commit & push if changed
      if: hashFiles('datos_nomivac_covid19.csv') != ''
      run: |-
        rm datos_nomivac_covid19.csv
        git config user.name "Automatic"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Update nomivac" || exit 0
        git push
