name: Download datos nomivac
 
on:
  workflow_dispatch:
  schedule:
    - cron:  '42 0,9,12,15,18,21 * * *'
 
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Get data nomivac from portal
      run: |-
        curl 'https://sisa.msal.gov.ar/datos/descargas/covid-19/files/datos_nomivac_covid19.csv' > datos_nomivac_covid19.csv
    - name: Agrupado 1
      run: |-
        head -1 datos_nomivac_covid19.csv | awk -F, '{print $7","$2","$1","$14",cantidad"}' > datos_nomivac_covid19_agrupados_edad_sexo_dosis.csv
        awk -F, '{if (NR!=1) a[$7","$2","$1","$14]++}END{for(i in a) { print i"," "\"" a[i] "\"" }}' datos_nomivac_covid19.csv | sort -k1 >> datos_nomivac_covid19_agrupados_edad_sexo_dosis.csv
        sed -i -r 's/,orden_dosis,cantidad/s,"orden_dosis","cantidad"/; s/,([12]),/,"\1",/gm;t' datos_nomivac_covid19_agrupados_edad_sexo_dosis.csv
    - name: Agrupado 2
      run: |-
        echo -n '"count",' > datos_nomivac_covid19_sin_fecha_sin_lote.csv
        head -1 datos_nomivac_covid19.csv | cut -d, -f11,15 --complement >> datos_nomivac_covid19_sin_fecha_sin_lote.csv
        tail -n +2 datos_nomivac_covid19.csv | cut -d, -f11,15 --complement | sort | uniq -c | sed 's/^ *//g; s/ /,/' >> datos_nomivac_covid19_sin_fecha_sin_lote.csv
        rm datos_nomivac_covid19.csv
    - name: Commit & push if changed
      run: |-
        git config user.name "Automatic"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Update nomivac" || exit 0
        git push
